spring:
  application:
    name: spring_web
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: sh
    password: sh
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  level:
    root: info
    com.sh: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.sh
  mapper-locations: classpath*:mappers/**/*-mapper.xml

server:
  servlet:
    context-path: /app

ftp:
  server:
    host: ssg-java3.iptime.org
    port: 21
    username: myftp
    password: myftp